name: Azure AKS CI-CD

on:
  push:
    branches:
      - main

env:
  REGISTRY: ${{ secrets.ACR_NAME }}.azurecr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to ACR
      run: az acr login --name ${{ secrets.ACR_NAME }}

    - name: Build & Push Images
      run: |
        docker build -t $REGISTRY/users-service:latest ./users-service
        docker build -t $REGISTRY/orders-service:latest ./orders-service
        docker push $REGISTRY/users-service:latest
        docker push $REGISTRY/orders-service:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v4
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.AKS_CLUSTER }}

    - name: Deploy Users
      run: kubectl set image deployment/users-deployment users=$REGISTRY/users-service:latest

    - name: Deploy Orders
      run: kubectl set image deployment/orders-deployment orders=$REGISTRY/orders-service:latest

    - name: Verify
      run: kubectl get pods
